name: Update Header with Build Info

on:
  push:
    branches:
      - main

jobs:
  generate-and-commit-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Main Branch
      uses: actions/checkout@v3
      with:
        path: src
        ref: main
        persist-credentials: false

    - name: Build Main
      working-directory: src
      shell: bash
      run: |
        cmake -B build -DENABLE_OPT=0 -DGLSLANG_TESTS=0
        cd build
        cmake --build .

    - name: Checkout Generated Files Branch
      uses: actions/checkout@v3
      with:
        path: dest
        ref: generated-files
        persist-credentials: false
      

    - name: Copy Files
      shell: bash
      run: |
        cp src/glslang dest/glslang
        cp src/SPIRV dest/SPIRV
        cp src/StandAlone dest/StandAlone

        mkdir -p dest/generated/glslang

        cp src/build/include/glslang/build_info.h dest/generated/glslang/build_info.h
        cp src/build/include/glslang/glsl_intrinsic_header.h dest/generated/glslang/glsl_intrinsic_header.h

    - name: Check For New Files
      id: newFiles
      working-directory: dest
      shell: bash
      run: |
        git add -A
        git status --porcelain | wc -l
        if [[ $(git status --porcelain | wc -l) -gt 0 ]]; then
          echo "::set-output name=hasNewFiles::true"
        else
          echo "::set-output name=hasNewFiles::false"
        fi

    - name: Push Commit
      if: ${{ steps.newFiles.outputs.hasNewFiles == 'true' }}
      working-directory: dest
      shell: bash
      run: |
        git config --global user.name lemz1
        git config --global user.email ${{ secrets.EMAIL }}
        git commit -m "Generate Files"
        git remote set-url --push origin https://x-access-token:${{ secrets.PAT }}@github.com/lemz1/glslang.git
        git push
