name: Update Header with Build Info

on:
  push:
    branches:
      - main

jobs:
  generate-and-commit-header:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Main Branch
      uses: actions/checkout@v3
      with:
        path: src
        ref: main
        persist-credentials: false

    - name: Build Main
      run: |
        cd src
        cmake -B build -DENABLE_OPT=0 -DGLSLANG_TESTS=0
        cd build
        cmake --build .

    - name: Checkout Header Branch
      uses: actions/checkout@v3
      with:
        path: dest
        ref: header
        persist-credentials: false
      

    - name: Copy File Test
      shell: bash
      run: |
        cp src/build/include/glslang/build_info.h dest/build_info.h
        cp src/build/include/glslang/glsl_intrinsic_header.h dest/glsl_intrinsic_header.h

    - name: Push Commit
      shell: bash
      run: |
        cd dest
        git config --global user.name lemz1
        git config --global user.email ${{ secrets.EMAIL }}
        git add -A
        git commit -m "Generate Headers"
        git remote set-url --push origin https://x-access-token:${{ secrets.PAT }}@github.com/lemz1/glslang.git
        git push
        